window.GH_DATA = {
	repo: { owner: "acme", name: "storefront" },
	pulls: {
		482: {
			title: "Add retry policy to checkout payments",
			author: "marina-dev",
			commits: 7,
			conversation: 12,
			checks: 4,
			base: "main",
			head: "feat/payment-retries",
		},
		483: {
			title: "Move catalog search to the new index",
			author: "theo-reviews",
			commits: 4,
			conversation: 3,
			checks: 4,
			base: "main",
			head: "feat/catalog-index",
		},
	},
	comments: {
		discussion_r1842: {
			author: "theo-reviews",
			age: "2 hours ago",
			body: "Should we also assert that the spinner is announced to screen readers?",
		},
	},
	files: [
		{
			path: "docs/payments.md",
			status: "modified",
			hunks: [
				{
					old: 12,
					new: 12,
					context: "## Checkout",
					lines: [
						" The checkout flow charges the customer when the order is confirmed.",
						" ",
						"-Failed charges are reported to the customer immediately.",
						"+Failed charges are retried with exponential backoff before the",
						"+customer sees an error.",
						"+",
						"+## Retry policy",
						"+",
						"+| Attempt | Delay |",
						"+| ------- | ----- |",
						"+| 1       | 250ms |",
						"+| 2       | 1s    |",
						" ",
						" See `src/payments/retry-policy.ts` for the implementation.",
					],
				},
			],
		},
		{
			path: "e2e/checkout.spec.ts",
			status: "added",
			hunks: [
				{
					old: 0,
					new: 1,
					lines: [
						'+import { expect, test } from "@playwright/test";',
						"+",
						'+test("retries a declined charge before failing", async ({ page }) => {',
						'+  await page.goto("/checkout?scenario=flaky-gateway");',
						'+  await page.getByRole("button", { name: "Pay now" }).click();',
						"+",
						'+  await expect(page.getByText("Processing payment")).toBeVisible();',
						'+  await expect(page.getByText("Order confirmed")).toBeVisible({',
						"+    timeout: 10_000,",
						"+  });",
						"+});",
					],
				},
			],
		},
		{
			path: "examples/node/package-lock.json",
			status: "modified",
			stat: { add: 38, del: 31 },
			hunks: [
				{
					old: 1,
					new: 1,
					lines: [
						" {",
						'   "name": "storefront-node-example",',
						'-  "version": "1.3.0",',
						'+  "version": "1.4.0",',
						'   "lockfileVersion": 3,',
						'   "requires": true,',
					],
				},
				{
					old: 214,
					new: 214,
					lines: [
						'     "node_modules/@acme/payments-sdk": {',
						'-      "version": "4.1.2",',
						'-      "resolved": "https://registry.npmjs.org/@acme/payments-sdk/-/payments-sdk-4.1.2.tgz",',
						'-      "integrity": "sha512-Qm9xR2Lw8...b2Pw==",',
						'+      "version": "4.2.0",',
						'+      "resolved": "https://registry.npmjs.org/@acme/payments-sdk/-/payments-sdk-4.2.0.tgz",',
						'+      "integrity": "sha512-Zr4cK7Vn1...f8Ka==",',
						'       "license": "MIT"',
						"     },",
					],
				},
			],
		},
		{
			path: "src/__tests__/checkout.ts",
			status: "modified",
			hunks: [
				{
					old: 8,
					new: 8,
					context: 'describe("checkout", () => {',
					lines: [
						'   it("charges the order total", async () => {',
						"     const gateway = createFakeGateway();",
						"-    const result = await checkout(order, gateway);",
						"+    const result = await checkout(order, gateway, {",
						"+      retryPolicy: noRetries,",
						"+    });",
						" ",
						'     expect(result.status).toBe("paid");',
						"     expect(gateway.charges).toHaveLength(1);",
					],
				},
			],
		},
		{
			path: "src/components/Button.spec.tsx",
			status: "modified",
			hunks: [
				{
					old: 15,
					new: 15,
					context: 'describe("Button", () => {',
					lines: [
						'   it("renders the label", () => {',
						"     render(<Button>Pay now</Button>);",
						'     expect(screen.getByRole("button")).toHaveTextContent("Pay now");',
						"   });",
						"+",
						'+  it("shows a spinner while loading", () => {',
						"+    render(<Button loading>Pay now</Button>);",
						'+    const button = screen.getByRole("button");',
						"+    expect(button).toBeDisabled();",
						'+    expect(button).toHaveAttribute("aria-busy", "true");',
						"+  });",
						" });",
					],
					comment: { after: 8, id: "discussion_r1842" },
				},
			],
		},
		{
			path: "src/components/Button.tsx",
			status: "modified",
			hunks: [
				{
					old: 1,
					new: 1,
					lines: [
						' import type { ButtonHTMLAttributes } from "react";',
						'+import { Spinner } from "./Spinner";',
						" ",
						" type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {",
						'   variant?: "primary" | "secondary";',
						"+  loading?: boolean;",
						" };",
						" ",
						'-export function Button({ variant = "primary", ...props }: ButtonProps) {',
						'+export function Button({ variant = "primary", loading = false, children, ...props }: ButtonProps) {',
						"   return (",
						"     <button",
						"       className={`btn btn-${variant}`}",
						"+      disabled={loading || props.disabled}",
						"+      aria-busy={loading}",
						"       {...props}",
						"-    />",
						"+    >",
						'+      {loading ? <Spinner size="small" /> : children}',
						"+    </button>",
						"   );",
						" }",
					],
				},
			],
		},
		{
			path: "src/components/CheckoutForm.test.tsx",
			status: "added",
			hunks: [
				{
					old: 0,
					new: 1,
					lines: [
						'+import { render, screen } from "@testing-library/react";',
						'+import userEvent from "@testing-library/user-event";',
						'+import { CheckoutForm } from "./CheckoutForm";',
						"+",
						'+it("disables the submit button while the charge is retried", async () => {',
						"+  const onSubmit = vi.fn(() => new Promise(() => {}));",
						"+  render(<CheckoutForm onSubmit={onSubmit} />);",
						"+",
						'+  await userEvent.click(screen.getByRole("button", { name: "Pay now" }));',
						"+",
						'+  expect(screen.getByRole("button", { name: "Pay now" })).toBeDisabled();',
						"+  expect(onSubmit).toHaveBeenCalledOnce();",
						"+});",
					],
				},
			],
		},
		{
			path: "src/components/CheckoutForm.tsx",
			status: "modified",
			hunks: [
				{
					old: 22,
					new: 22,
					context: "export function CheckoutForm({ onSubmit }: CheckoutFormProps) {",
					lines: [
						"   const [error, setError] = useState<string | null>(null);",
						"+  const [submitting, setSubmitting] = useState(false);",
						" ",
						"   async function handleSubmit(event: FormEvent) {",
						"     event.preventDefault();",
						"-    const result = await onSubmit(readForm(event.currentTarget));",
						'-    if (result.status === "declined") setError(result.message);',
						"+    setSubmitting(true);",
						"+    try {",
						"+      const result = await onSubmit(readForm(event.currentTarget));",
						'+      if (result.status === "declined") setError(result.message);',
						"+    } finally {",
						"+      setSubmitting(false);",
						"+    }",
						"   }",
					],
				},
				{
					old: 48,
					new: 54,
					context: "export function CheckoutForm({ onSubmit }: CheckoutFormProps) {",
					lines: [
						"       <PaymentFields />",
						"       {error && <ErrorMessage>{error}</ErrorMessage>}",
						'-      <Button type="submit">Pay now</Button>',
						'+      <Button type="submit" loading={submitting}>',
						"+        Pay now",
						"+      </Button>",
						"     </form>",
						"   );",
						" }",
					],
				},
			],
		},
		{
			path: "src/config.ts",
			status: "modified",
			hunks: [
				{
					old: 4,
					new: 4,
					context: "export const config = {",
					lines: [
						'   apiUrl: env("API_URL"),',
						'   currency: env("CURRENCY", "USD"),',
						"+  payments: {",
						'+    maxRetries: Number(env("PAYMENT_MAX_RETRIES", "3")),',
						'+    baseDelayMs: Number(env("PAYMENT_BASE_DELAY_MS", "250")),',
						"+    timeoutMs: 10_000,",
						"+  },",
						" } as const;",
					],
				},
			],
		},
		{
			path: "src/generated/client.ts",
			status: "modified",
			hunks: [
				{
					old: 1,
					new: 1,
					lines: [
						"-// Code generated by openapi-gen v2.8.1. DO NOT EDIT.",
						"+// Code generated by openapi-gen v2.9.0. DO NOT EDIT.",
						" ",
						" export interface ChargeRequest {",
						"   orderId: string;",
						"   amount: number;",
					],
				},
				{
					old: 88,
					new: 88,
					context: "export interface ChargeResponse {",
					lines: [
						'   status: "paid" | "declined" | "pending";',
						"   gatewayReference: string;",
						"+  retryAfterMs?: number;",
						"+}",
						"+",
						"+export interface RetryableError {",
						'+  code: "GATEWAY_TIMEOUT" | "RATE_LIMITED";',
						"+  retryAfterMs: number;",
						" }",
					],
				},
			],
		},
		{
			path: "src/payments/__tests__/gateway.ts",
			status: "added",
			hunks: [
				{
					old: 0,
					new: 1,
					lines: [
						'+import { describe, expect, it } from "vitest";',
						'+import { isRetryable } from "../gateway";',
						"+",
						'+describe("isRetryable", () => {',
						"+  it.each([",
						'+    ["GATEWAY_TIMEOUT", true],',
						'+    ["RATE_LIMITED", true],',
						'+    ["CARD_DECLINED", false],',
						'+  ])("%s → %s", (code, expected) => {',
						"+    expect(isRetryable({ code })).toBe(expected);",
						"+  });",
						"+});",
					],
				},
			],
		},
		{
			path: "src/payments/checkout.spec.ts",
			status: "modified",
			hunks: [
				{
					old: 30,
					new: 30,
					context: 'describe("checkout", () => {',
					lines: [
						'     expect(result.status).toBe("paid");',
						"   });",
						" ",
						'+  it("retries a timeout and then succeeds", async () => {',
						"+    const gateway = createFakeGateway({",
						"+      responses: [timeout(), paid()],",
						"+    });",
						"+",
						"+    const result = await checkout(order, gateway, { retryPolicy });",
						"+",
						'+    expect(result.status).toBe("paid");',
						"+    expect(gateway.charges).toHaveLength(2);",
						"+  });",
						"+",
						'   it("does not retry a declined card", async () => {',
					],
				},
			],
		},
		{
			path: "src/payments/checkout.ts",
			status: "modified",
			hunks: [
				{
					old: 1,
					new: 1,
					lines: [
						' import { config } from "../config";',
						'-import { charge } from "./gateway";',
						'+import { charge, isRetryable } from "./gateway";',
						'+import { type RetryPolicy, defaultRetryPolicy, withRetries } from "./retry-policy";',
						" ",
						" export async function checkout(",
						"   order: Order,",
						"   gateway: Gateway,",
						"+  { retryPolicy = defaultRetryPolicy }: { retryPolicy?: RetryPolicy } = {},",
						" ) {",
						"-  return charge(gateway, order);",
						"+  return withRetries(() => charge(gateway, order), retryPolicy, isRetryable);",
						" }",
					],
				},
			],
		},
		{
			path: "src/payments/gateway.ts",
			status: "modified",
			hunks: [
				{
					old: 40,
					new: 40,
					context: "export async function charge(gateway: Gateway, order: Order) {",
					lines: [
						"   return gateway.charge({ orderId: order.id, amount: order.total });",
						" }",
						" ",
						'+const RETRYABLE_CODES = new Set(["GATEWAY_TIMEOUT", "RATE_LIMITED"]);',
						"+",
						"+export function isRetryable(error: { code: string }) {",
						"+  return RETRYABLE_CODES.has(error.code);",
						"+}",
						"+",
						" export function toCents(amount: number) {",
					],
				},
			],
		},
		{
			path: "src/payments/retry-policy.spec.ts",
			status: "added",
			hunks: [
				{
					old: 0,
					new: 1,
					lines: [
						'+import { describe, expect, it, vi } from "vitest";',
						'+import { withRetries } from "./retry-policy";',
						"+",
						'+describe("withRetries", () => {',
						'+  it("stops after the maximum number of attempts", async () => {',
						'+    const task = vi.fn().mockRejectedValue({ code: "GATEWAY_TIMEOUT" });',
						"+    const policy = { maxRetries: 2, baseDelayMs: 0 };",
						"+",
						"+    await expect(withRetries(task, policy, () => true)).rejects.toThrow();",
						"+",
						"+    expect(task).toHaveBeenCalledTimes(3);",
						"+  });",
						"+});",
					],
				},
			],
		},
		{
			path: "src/payments/retry-policy.ts",
			status: "added",
			hunks: [
				{
					old: 0,
					new: 1,
					lines: [
						'+import { config } from "../config";',
						"+",
						"+export type RetryPolicy = {",
						"+  maxRetries: number;",
						"+  baseDelayMs: number;",
						"+};",
						"+",
						"+export const defaultRetryPolicy: RetryPolicy = config.payments;",
						"+",
						"+export async function withRetries<T>(",
						"+  task: () => Promise<T>,",
						"+  policy: RetryPolicy,",
						"+  isRetryable: (error: unknown) => boolean,",
						"+): Promise<T> {",
						"+  for (let attempt = 0; ; attempt++) {",
						"+    try {",
						"+      return await task();",
						"+    } catch (error) {",
						"+      if (attempt >= policy.maxRetries || !isRetryable(error)) throw error;",
						"+      await sleep(policy.baseDelayMs * 2 ** attempt);",
						"+    }",
						"+  }",
						"+}",
					],
				},
			],
		},
		{
			path: "src/test-utils.ts",
			status: "modified",
			hunks: [
				{
					old: 12,
					new: 12,
					context: "export function createFakeGateway(options: FakeGatewayOptions = {}) {",
					lines: [
						"   const charges: ChargeRequest[] = [];",
						"+  const responses = [...(options.responses ?? [])];",
						" ",
						"   return {",
						"     charges,",
						"     async charge(request: ChargeRequest) {",
						"       charges.push(request);",
						'-      return { status: "paid", gatewayReference: "fake_ref" };',
						"+      const next = responses.shift() ?? paid();",
						"+      if (next instanceof Error) throw next;",
						"+      return next;",
						"     },",
						"   };",
					],
				},
			],
		},
		{
			path: "src/utils/format.test.ts",
			status: "modified",
			hunks: [
				{
					old: 3,
					new: 3,
					context: 'import { formatMoney } from "./format";',
					lines: [
						' it("formats dollars", () => {',
						'   expect(formatMoney(1999, "USD")).toBe("$19.99");',
						" });",
						"+",
						'+it("formats zero-decimal currencies", () => {',
						'+  expect(formatMoney(1999, "JPY")).toBe("¥1,999");',
						"+});",
					],
				},
			],
		},
		{
			path: "src/utils/format.ts",
			status: "modified",
			hunks: [
				{
					old: 1,
					new: 1,
					lines: [
						'+const ZERO_DECIMAL = new Set(["JPY", "KRW"]);',
						"+",
						" export function formatMoney(cents: number, currency: string) {",
						"-  const amount = cents / 100;",
						"+  const amount = ZERO_DECIMAL.has(currency) ? cents : cents / 100;",
						'   return new Intl.NumberFormat("en-US", {',
						'     style: "currency",',
						"     currency,",
						"   }).format(amount);",
					],
				},
			],
		},
		{
			path: "package.json",
			status: "modified",
			hunks: [
				{
					old: 18,
					new: 18,
					lines: [
						'   "dependencies": {',
						'-    "@acme/payments-sdk": "^4.1.2",',
						'+    "@acme/payments-sdk": "^4.2.0",',
						'     "react": "^19.2.0",',
						'     "react-dom": "^19.2.0"',
						"   },",
					],
				},
			],
		},
		{
			path: "pnpm-lock.yaml",
			status: "modified",
			stat: { add: 214, del: 187 },
			hunks: [
				{
					old: 42,
					new: 42,
					context: "importers:",
					lines: [
						"     dependencies:",
						"       '@acme/payments-sdk':",
						"-        specifier: ^4.1.2",
						"-        version: 4.1.2",
						"+        specifier: ^4.2.0",
						"+        version: 4.2.0",
						"       react:",
						"         specifier: ^19.2.0",
						"         version: 19.2.0",
					],
				},
				{
					old: 318,
					new: 318,
					context: "packages:",
					lines: [
						"-  '@acme/payments-sdk@4.1.2':",
						"-    resolution: {integrity: sha512-Qm9xR2Lw8...b2Pw==}",
						"+  '@acme/payments-sdk@4.2.0':",
						"+    resolution: {integrity: sha512-Zr4cK7Vn1...f8Ka==}",
						"     engines: {node: '>=20'}",
					],
				},
			],
		},
		{
			path: "README.md",
			status: "modified",
			hunks: [
				{
					old: 24,
					new: 24,
					context: "## Configuration",
					lines: [
						" | `API_URL` | Storefront API base URL |",
						" | `CURRENCY` | Default currency code |",
						"+| `PAYMENT_MAX_RETRIES` | Retries for retryable gateway errors (default 3) |",
						"+| `PAYMENT_BASE_DELAY_MS` | First retry delay in milliseconds (default 250) |",
					],
				},
			],
		},
	],
};
