(() => {
	const PRESETS = [
		{
			id: "tests",
			name: "Tests",
			description: "Spec and test files, and everything inside __tests__ folders.",
			rules: ["**/*.spec.*", "**/*.test.*", "**/__tests__/**"],
		},
		{
			id: "lockfiles",
			name: "Lockfiles",
			description: "Lockfiles generated by npm, Yarn, and pnpm.",
			rules: ["**/package-lock.json", "**/yarn.lock", "**/pnpm-lock.yaml"],
		},
	];

	const uid = () => Math.random().toString(36).slice(2, 9);

	function firstInstallState() {
		return {
			mode: "manual",
			treeFiltering: true,
			presets: Object.fromEntries(PRESETS.map((p) => [p.id, { enabled: false, rules: [...p.rules] }])),
			customRules: [],
			alwaysShow: [],
			activePRs: {},
		};
	}

	function demoState() {
		const s = firstInstallState();
		s.presets.tests.enabled = true;
		s.presets.lockfiles.enabled = true;
		s.customRules = [
			{ id: uid(), pattern: "**/generated/**", enabled: true },
			{ id: uid(), pattern: "docs/**", enabled: false },
		];
		s.alwaysShow = [{ id: uid(), pattern: "src/payments/checkout.spec.ts", enabled: true }];
		return s;
	}

	const regexCache = new Map();

	function toRegex(pattern) {
		if (regexCache.has(pattern)) return regexCache.get(pattern);
		let src = "";
		let i = 0;
		const p = pattern.trim().replace(/^\.?\//, "");
		while (i < p.length) {
			if (p.startsWith("**/", i)) {
				src += "(?:.*/)?";
				i += 3;
			} else if (p.startsWith("/**", i) && i + 3 === p.length) {
				src += "/.*";
				i += 3;
			} else if (p.startsWith("**", i)) {
				src += ".*";
				i += 2;
			} else if (p[i] === "*") {
				src += "[^/]*";
				i++;
			} else if (p[i] === "?") {
				src += "[^/]";
				i++;
			} else {
				src += p[i].replace(/[.+^${}()|[\]\\]/g, "\\$&");
				i++;
			}
		}
		const re = new RegExp(`^${src}$`);
		regexCache.set(pattern, re);
		return re;
	}

	function match(pattern, path) {
		if (!pattern || !pattern.trim()) return false;
		return toRegex(pattern).test(path);
	}

	function validatePattern(pattern) {
		const p = pattern.trim();
		if (!p) return { ok: false, error: "Enter a path or pattern." };
		if (p.startsWith("/")) return { ok: false, error: "Use a repository-relative path. Remove the leading /." };
		if (p.includes("\\")) return { ok: false, error: "Use forward slashes (/) in paths." };
		if (/\s/.test(p)) return { ok: false, error: "Patterns cannot contain spaces." };
		if (/\*\*\*/.test(p)) return { ok: false, error: "Use * or **, not ***." };
		return { ok: true, error: null };
	}

	const bus = new EventTarget();
	let ns = "default";
	let state = demoState();
	let showingAll = false;
	const revealed = new Set();
	let lastDetail = null;
	let applyQueued = false;

	const storageKey = () => `fh-proto:${ns}`;

	function load() {
		try {
			const raw = localStorage.getItem(storageKey());
			state = raw ? JSON.parse(raw) : demoState();
		} catch {
			state = demoState();
		}
	}

	function save() {
		try {
			localStorage.setItem(storageKey(), JSON.stringify(state));
		} catch {}
	}

	const prKey = () => (window.GH ? GH.prKey : "acme/storefront#482");

	function isActive() {
		return state.mode === "automatic" || !!state.activePRs[prKey()];
	}

	function isFiltering() {
		return isActive() && !showingAll;
	}

	function evaluate(path) {
		let hideReason = null;
		for (const p of PRESETS) {
			const ps = state.presets[p.id];
			if (!ps?.enabled) continue;
			const rule = ps.rules.find((r) => match(r, path));
			if (rule) {
				hideReason = { kind: "preset", presetId: p.id, presetName: p.name, pattern: rule };
				break;
			}
		}
		if (!hideReason) {
			const rule = state.customRules.find((r) => r.enabled && match(r.pattern, path));
			if (rule) hideReason = { kind: "custom", ruleId: rule.id, pattern: rule.pattern };
		}
		const always = state.alwaysShow.find((r) => r.enabled !== false && match(r.pattern, path));
		if (always && hideReason)
			return { hidden: false, kept: true, reason: { kind: "always", ruleId: always.id, pattern: always.pattern }, overridden: hideReason };
		if (always) return { hidden: false, kept: false, reason: { kind: "always", ruleId: always.id, pattern: always.pattern }, overridden: null };
		return { hidden: !!hideReason, kept: false, reason: hideReason, overridden: null };
	}

	function reasonLabel(reason) {
		if (!reason) return "";
		if (reason.kind === "preset") return `${reason.presetName} preset`;
		if (reason.kind === "custom") return "Custom rule";
		return "Always show";
	}

	function enabledRuleCount() {
		let n = 0;
		for (const p of PRESETS) if (state.presets[p.id]?.enabled) n += state.presets[p.id].rules.length;
		n += state.customRules.filter((r) => r.enabled).length;
		return n;
	}

	function apply() {
		const root = window.GH?.root;
		if (!root) return;
		const filtering = isFiltering();
		const hiddenDiff = new Set();
		const hiddenTree = new Set();
		const evals = new Map();
		const ev = (p) => {
			if (!evals.has(p)) evals.set(p, evaluate(p));
			return evals.get(p);
		};
		for (const el of root.querySelectorAll(".gh-file[data-path]")) {
			const path = el.dataset.path;
			const e = ev(path);
			const isRevealed = filtering && e.hidden && revealed.has(path);
			const hide = filtering && e.hidden && !isRevealed;
			el.classList.toggle("fh-hidden", hide);
			el.classList.toggle("fh-revealed", isRevealed);
			el.dataset.fhState = hide ? "hidden" : isRevealed ? "revealed" : e.kept && filtering ? "kept" : "";
			el.dataset.fhMatch = e.hidden ? "hide" : e.kept ? "kept" : e.reason ? "always" : "";
			el.dataset.fhReason = e.reason ? reasonLabel(e.reason) : "";
			el.dataset.fhPattern = e.reason ? e.reason.pattern : "";
			if (hide) hiddenDiff.add(path);
		}
		for (const el of root.querySelectorAll(".gh-tree-file[data-path]")) {
			const path = el.dataset.path;
			const e = ev(path);
			const isRevealed = filtering && e.hidden && revealed.has(path);
			const hiddenInDiff = filtering && e.hidden && !isRevealed;
			const hide = hiddenInDiff && state.treeFiltering;
			el.classList.toggle("fh-hidden", hide);
			el.classList.toggle("fh-revealed", isRevealed);
			el.dataset.fhState = hide
				? "hidden"
				: hiddenInDiff
					? "diff-hidden"
					: isRevealed
						? "revealed"
						: e.kept && filtering
							? "kept"
							: "";
			el.dataset.fhMatch = e.hidden ? "hide" : e.kept ? "kept" : e.reason ? "always" : "";
			el.dataset.fhReason = e.reason ? reasonLabel(e.reason) : "";
			el.dataset.fhPattern = e.reason ? e.reason.pattern : "";
			if (hide) hiddenTree.add(path);
		}
		for (const d of [...root.querySelectorAll(".gh-tree-dir")].reverse()) {
			const files = d.querySelectorAll(".gh-tree-file");
			const allHidden = files.length > 0 && [...files].every((f) => f.classList.contains("fh-hidden"));
			d.classList.toggle("fh-hidden", allHidden);
		}
		const hiddenPaths = [...new Set([...hiddenDiff, ...hiddenTree])];
		const all = window.GH ? GH.paths : [];
		const matchPaths = all.filter((p) => ev(p).hidden);
		const keptPaths = all.filter((p) => ev(p).kept);
		const byReason = {};
		for (const p of hiddenPaths) {
			const label = reasonLabel(ev(p).reason);
			byReason[label] = (byReason[label] || 0) + 1;
		}
		lastDetail = {
			prKey: prKey(),
			mode: state.mode,
			treeFiltering: state.treeFiltering,
			active: isActive(),
			showingAll,
			filtering,
			hiddenCount: hiddenPaths.length,
			hiddenPaths,
			hiddenInDiff: [...hiddenDiff],
			hiddenInTree: [...hiddenTree],
			byReason,
			matchCount: matchPaths.length,
			matchPaths,
			keptPaths,
			revealed: [...revealed].filter((p) => ev(p).hidden),
			loadedCount: window.GH ? GH.loadedPaths().length : 0,
			totalCount: all.length,
			ruleCount: enabledRuleCount(),
		};
		bus.dispatchEvent(new CustomEvent("change", { detail: lastDetail }));
	}

	function scheduleApply() {
		if (applyQueued) return;
		applyQueued = true;
		queueMicrotask(() => {
			applyQueued = false;
			apply();
		});
	}

	function commit(mutator) {
		mutator(state);
		save();
		apply();
		bus.dispatchEvent(new CustomEvent("settings", { detail: state }));
	}

	function handleHash() {
		const id = decodeURIComponent(location.hash.slice(1));
		if (!id || !window.GH?.root) return;
		for (const t of GH.root.querySelectorAll(".target")) t.classList.remove("target");
		const run = () => {
			const el = document.getElementById(id);
			if (!el) return false;
			const fileEl = el.closest(".gh-file");
			if (!fileEl) return true;
			const path = fileEl.dataset.path;
			const e = evaluate(path);
			const kind = el === fileEl ? "file" : "comment";
			if (kind === "comment") el.classList.add("target");
			if (isFiltering() && e.hidden && !revealed.has(path)) {
				revealed.add(path);
				apply();
				bus.dispatchEvent(
					new CustomEvent("reveal", { detail: { path, kind, targetId: id, reason: e.reason, label: reasonLabel(e.reason) } }),
				);
			}
			fileEl.classList.remove("collapsed");
			requestAnimationFrame(() => el.scrollIntoView({ behavior: "smooth", block: kind === "comment" ? "center" : "start" }));
			return true;
		};
		if (!run()) GH.loadMore().then(run);
	}

	const api = {
		presets: PRESETS,
		match,
		validatePattern,
		evaluate,
		reasonLabel,
		init({ namespace = "default" } = {}) {
			ns = namespace;
			load();
			const root = window.GH?.root;
			if (root) {
				new MutationObserver(scheduleApply).observe(root.querySelector("#gh-files"), { childList: true });
			}
			window.addEventListener("hashchange", handleHash);
			window.addEventListener("storage", (e) => {
				if (e.key === storageKey()) {
					load();
					apply();
					bus.dispatchEvent(new CustomEvent("settings", { detail: state }));
				}
			});
			apply();
			if (location.hash) setTimeout(handleHash, 50);
			return api;
		},
		on(type, cb) {
			const fn = (e) => cb(e.detail);
			bus.addEventListener(type, fn);
			if (type === "change" && lastDetail) cb(lastDetail);
			return () => bus.removeEventListener(type, fn);
		},
		get state() {
			return state;
		},
		get detail() {
			return lastDetail;
		},
		isActive,
		isFiltering,
		activate() {
			showingAll = false;
			if (state.mode === "manual") commit((s) => (s.activePRs[prKey()] = true));
			else apply();
		},
		deactivate() {
			showingAll = false;
			revealed.clear();
			if (state.mode === "manual") commit((s) => delete s.activePRs[prKey()]);
			else {
				showingAll = true;
				apply();
			}
		},
		showAll() {
			showingAll = true;
			apply();
		},
		restore() {
			if (!isActive()) return api.activate();
			showingAll = false;
			apply();
		},
		toggle() {
			if (isFiltering()) api.showAll();
			else api.restore();
		},
		hideRevealed(path) {
			if (path) revealed.delete(path);
			else revealed.clear();
			if (location.hash) history.replaceState(null, "", location.pathname + location.search);
			for (const t of GH.root.querySelectorAll(".target")) t.classList.remove("target");
			apply();
		},
		setMode(mode) {
			showingAll = false;
			commit((s) => (s.mode = mode));
		},
		setTreeFiltering(on) {
			commit((s) => (s.treeFiltering = !!on));
		},
		setPresetEnabled(id, on) {
			commit((s) => (s.presets[id].enabled = !!on));
		},
		setPresetRules(id, rules) {
			commit((s) => (s.presets[id].rules = rules.map((r) => r.trim()).filter(Boolean)));
		},
		addPresetRule(id, pattern) {
			commit((s) => s.presets[id].rules.push(pattern.trim()));
		},
		updatePresetRule(id, index, pattern) {
			commit((s) => (s.presets[id].rules[index] = pattern.trim()));
		},
		removePresetRule(id, index) {
			commit((s) => s.presets[id].rules.splice(index, 1));
		},
		restorePreset(id) {
			const def = PRESETS.find((p) => p.id === id);
			commit((s) => (s.presets[id].rules = [...def.rules]));
		},
		isPresetModified(id) {
			const def = PRESETS.find((p) => p.id === id);
			const cur = state.presets[id].rules;
			return cur.length !== def.rules.length || cur.some((r, i) => r !== def.rules[i]);
		},
		addCustomRule(pattern) {
			const rule = { id: uid(), pattern: pattern.trim(), enabled: true };
			commit((s) => s.customRules.push(rule));
			return rule;
		},
		updateCustomRule(id, patch) {
			commit((s) => Object.assign(s.customRules.find((r) => r.id === id), patch));
		},
		removeCustomRule(id) {
			commit((s) => (s.customRules = s.customRules.filter((r) => r.id !== id)));
		},
		addAlwaysShow(pattern) {
			const rule = { id: uid(), pattern: pattern.trim(), enabled: true };
			commit((s) => s.alwaysShow.push(rule));
			return rule;
		},
		updateAlwaysShow(id, patch) {
			commit((s) => Object.assign(s.alwaysShow.find((r) => r.id === id), patch));
		},
		removeAlwaysShow(id) {
			commit((s) => (s.alwaysShow = s.alwaysShow.filter((r) => r.id !== id)));
		},
		matchingPaths(pattern) {
			return (window.GH ? GH.paths : window.GH_DATA.files.map((f) => f.path)).filter((p) => match(pattern, p));
		},
		get samplePaths() {
			return window.GH ? GH.paths : window.GH_DATA.files.map((f) => f.path);
		},
		resetToFirstInstall() {
			showingAll = false;
			revealed.clear();
			commit((s) => Object.assign(s, firstInstallState()));
		},
		loadDemo() {
			showingAll = false;
			revealed.clear();
			commit((s) => Object.assign(s, demoState()));
		},
		apply,
	};

	window.FH = api;
})();
