import type { Evaluation, PresetId, Reason, Settings } from "./types";
export const presets: {
	id: PresetId;
	name: string;
	description: string;
	rules: string[];
}[] = [
	{
		id: "tests",
		name: "Tests",
		description:
			"Spec and test files, and everything inside __tests__ folders.",
		rules: ["**/*.spec.*", "**/*.test.*", "**/__tests__/**"],
	},
	{
		id: "lockfiles",
		name: "Lockfiles",
		description: "Lockfiles generated by npm, Yarn, and pnpm.",
		rules: ["**/package-lock.json", "**/yarn.lock", "**/pnpm-lock.yaml"],
	},
];
export function validatePattern(
	pattern: string,
	list: string[] = [],
): string | null {
	const p = pattern.trim();
	if (!p) return "Enter a path or pattern.";
	if (p.startsWith("/"))
		return "Use a repository-relative path. Remove the leading /.";
	if (p.includes("\\")) return "Use forward slashes (/) in paths.";
	if (p.includes("***")) return "Use * or **, not ***.";
	if (list.includes(p)) return "This rule is already in the list.";
	return null;
}
const compiled = new Map<string, RegExp>();
export function matches(pattern: string, path: string): boolean {
	if (validatePattern(pattern)) return false;
	let regex = compiled.get(pattern);
	if (!regex) {
		let p = pattern.trim().replace(/^\.\//, "");
		if (p.endsWith("/")) p += "**";
		let source = "";
		for (let i = 0; i < p.length; ) {
			if (p.startsWith("**/", i)) {
				source += "(?:.*/)?";
				i += 3;
			} else if (p.startsWith("**", i)) {
				source += ".*";
				i += 2;
			} else if (p[i] === "*") {
				source += "[^/]*";
				i++;
			} else if (p[i] === "?") {
				source += "[^/]";
				i++;
			} else {
				source += (p[i] ?? "").replace(/[.+^${}()|[\]\\]/g, "\\$&");
				i++;
			}
		}
		regex = new RegExp(`^${source}$`);
		compiled.set(pattern, regex);
	}
	return regex.test(path);
}
export function presetRules(settings: Settings, id: PresetId): string[] {
	return (
		settings.presets[id].rules ?? presets.find((p) => p.id === id)?.rules ?? []
	);
}
export function enabledRuleCount(settings: Settings): number {
	return (
		presets.reduce(
			(n, p) =>
				n +
				(settings.presets[p.id].enabled
					? presetRules(settings, p.id).length
					: 0),
			0,
		) + settings.customRules.filter((r) => r.enabled).length
	);
}
export function evaluate(path: string, settings: Settings): Evaluation {
	let reason: Reason | null = null;
	for (const preset of presets) {
		if (!settings.presets[preset.id].enabled) continue;
		const pattern = presetRules(settings, preset.id).find((p) =>
			matches(p, path),
		);
		if (pattern) {
			reason = { kind: "preset", presetId: preset.id, pattern };
			break;
		}
	}
	if (!reason) {
		const custom = settings.customRules.find(
			(r) => r.enabled && matches(r.pattern, path),
		);
		if (custom)
			reason = { kind: "custom", ruleId: custom.id, pattern: custom.pattern };
	}
	const always = settings.alwaysShow.find((r) => matches(r.pattern, path));
	if (always && reason)
		return {
			matching: false,
			kept: true,
			reason: { kind: "always", ruleId: always.id, pattern: always.pattern },
		};
	return { matching: !!reason, kept: false, reason };
}
export function reasonLabel(reason: Reason): string {
	return reason.kind === "preset"
		? `${presets.find((p) => p.id === reason.presetId)?.name} preset (${reason.pattern})`
		: `${reason.kind === "custom" ? "Custom rule" : "Always show rule"} (${reason.pattern})`;
}
