export type PresetId = "tests" | "lockfiles";

export type Preset = {
	id: PresetId;
	name: string;
	description: string;
	rules: readonly string[];
};

export const PRESETS: readonly Preset[] = [
	{
		id: "tests",
		name: "Tests",
		description:
			"Spec and test files, and everything inside __tests__ folders.",
		rules: ["**/*.spec.*", "**/*.test.*", "**/__tests__/**"],
	},
	{
		id: "lockfiles",
		name: "Lockfiles",
		description: "Lockfiles generated by npm, Yarn, and pnpm.",
		rules: ["**/package-lock.json", "**/yarn.lock", "**/pnpm-lock.yaml"],
	},
];

export type PresetState = { enabled: boolean; rules?: string[] };

export type CustomRule = { id: string; pattern: string; enabled: boolean };

export type AlwaysShowRule = { id: string; pattern: string };

export type RuleSettings = {
	presets: Record<PresetId, PresetState>;
	customRules: CustomRule[];
	alwaysShow: AlwaysShowRule[];
};

export type Reason =
	| { kind: "preset"; presetId: PresetId; pattern: string }
	| { kind: "custom"; ruleId: string; pattern: string }
	| { kind: "always"; ruleId: string; pattern: string };

export type Evaluation = {
	matching: boolean;
	kept: boolean;
	reason: Reason | null;
	overridden: Reason | null;
};

export type ValidationMessages = {
	empty: string;
	leadingSlash: string;
	backslash: string;
	stars: string;
	duplicate: string;
};

const DEFAULT_MESSAGES: ValidationMessages = {
	empty: "Enter a path or pattern.",
	leadingSlash: "Use a repository-relative path. Remove the leading /.",
	backslash: "Use forward slashes (/) in paths.",
	stars: "Use * or **, not ***.",
	duplicate: "This rule is already in the list.",
};

const compiled = new Map<string, RegExp>();

function escapeLiteral(character: string) {
	return character.replace(/[.+^${}()|[\]\\]/g, "\\$&");
}

function translate(pattern: string) {
	let source = "";
	let index = 0;
	while (index < pattern.length) {
		if (pattern.startsWith("**/", index)) {
			source += "(?:.*/)?";
			index += 3;
		} else if (
			pattern.startsWith("/**", index) &&
			index + 3 === pattern.length
		) {
			source += "/.*";
			index += 3;
		} else if (pattern.startsWith("**", index)) {
			source += ".*";
			index += 2;
		} else if (pattern[index] === "*") {
			source += "[^/]*";
			index += 1;
		} else if (pattern[index] === "?") {
			source += "[^/]";
			index += 1;
		} else {
			source += escapeLiteral(pattern[index] ?? "");
			index += 1;
		}
	}
	return source;
}

function normalizePattern(pattern: string) {
	const anchored = pattern.trim().replace(/^\.?\//, "");
	return anchored.endsWith("/") ? `${anchored}**` : anchored;
}

function compile(pattern: string) {
	let expression = compiled.get(pattern);
	if (!expression) {
		expression = new RegExp(`^${translate(normalizePattern(pattern))}$`);
		compiled.set(pattern, expression);
	}
	return expression;
}

export function matchesPattern(pattern: string, path: string) {
	if (!pattern.trim()) return false;
	return compile(pattern).test(path);
}

export function validatePattern(
	pattern: string,
	list: readonly string[],
	messages: ValidationMessages = DEFAULT_MESSAGES,
): string | null {
	const value = pattern.trim();
	if (!value) return messages.empty;
	if (value.startsWith("/")) return messages.leadingSlash;
	if (value.includes("\\")) return messages.backslash;
	if (value.includes("***")) return messages.stars;
	if (list.includes(value)) return messages.duplicate;
	return null;
}

export function presetById(id: PresetId): Preset {
	const preset = PRESETS.find((candidate) => candidate.id === id);
	if (!preset) throw new Error(`Unknown preset ${id}`);
	return preset;
}

export function defaultRules(id: PresetId): readonly string[] {
	return presetById(id).rules;
}

export function presetRules(
	settings: RuleSettings,
	id: PresetId,
): readonly string[] {
	return settings.presets[id].rules ?? defaultRules(id);
}

export function isPresetModified(settings: RuleSettings, id: PresetId) {
	return settings.presets[id].rules !== undefined;
}

function hideReason(path: string, settings: RuleSettings): Reason | null {
	for (const preset of PRESETS) {
		if (!settings.presets[preset.id].enabled) continue;
		const pattern = presetRules(settings, preset.id).find((rule) =>
			matchesPattern(rule, path),
		);
		if (pattern) return { kind: "preset", presetId: preset.id, pattern };
	}
	const custom = settings.customRules.find(
		(rule) => rule.enabled && matchesPattern(rule.pattern, path),
	);
	return custom
		? { kind: "custom", ruleId: custom.id, pattern: custom.pattern }
		: null;
}

export function evaluate(path: string, settings: RuleSettings): Evaluation {
	const hidden = hideReason(path, settings);
	const always = settings.alwaysShow.find((rule) =>
		matchesPattern(rule.pattern, path),
	);
	if (always) {
		const reason: Reason = {
			kind: "always",
			ruleId: always.id,
			pattern: always.pattern,
		};
		return {
			matching: false,
			kept: hidden !== null,
			reason,
			overridden: hidden,
		};
	}
	return {
		matching: hidden !== null,
		kept: false,
		reason: hidden,
		overridden: null,
	};
}

export function reasonLabel(reason: Reason | null) {
	if (!reason) return "";
	if (reason.kind === "preset")
		return `${presetById(reason.presetId).name} preset`;
	if (reason.kind === "custom") return "Custom rule";
	return "Always show";
}

export function reasonPhrase(reason: Reason | null) {
	const label = reasonLabel(reason);
	if (label === "Custom rule") return "a custom rule";
	return label ? `the ${label}` : "a rule";
}

export function enabledRuleCount(settings: RuleSettings) {
	const presetCount = PRESETS.filter(
		(preset) => settings.presets[preset.id].enabled,
	).reduce(
		(total, preset) => total + presetRules(settings, preset.id).length,
		0,
	);
	return (
		presetCount + settings.customRules.filter((rule) => rule.enabled).length
	);
}
